#  该YAML配置文件用于Spring Cloud Gateway网关服务，主要实现如下功能：
#
#    1. **服务路由**：将请求路径如`/mall-auth/**`转发到对应微服务（如`mall-auth`），并去除第一级路径。
#    2. **服务发现**：启用服务发现定位器，支持通过服务名进行负载均衡。
#    3. **安全配置**：
#    - 忽略部分路径的安全校验（如接口文档、静态资源、认证相关接口等）。
#    - 配置JWT资源服务器的公钥地址。
#    4. **Redis连接**：配置本地Redis数据库连接信息。
#    5. **监控管理**：开启所有Actuator端点，便于监控和管理应用。


server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #设置Spring MVC的路径匹配策略为Ant Path Matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启用服务发现定位器
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        # 定义一个名为mall-auth的服务路由配置
        - id: mall-auth
          # 指定服务的URI，使用负载均衡策略发现服务
          uri: lb://mall-auth
          # 配置路由的断言，用于匹配请求路径
          predicates:
            # 匹配以/mall-auth/开头的请求路径
            - Path=/mall-auth/**
          # 定义应用于该路由的过滤器
          filters:
            # 移除请求路径的第一个路径段
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/mall-auth/rsa/publicKey' #配置RSA的公钥访问地址
  # 配置Redis数据库的连接信息
  redis:
    # 指定使用的数据库索引，默认为0
    database: 0
    # 指定Redis服务器的端口号，默认为6379
    port: 6379
    # 指定Redis服务器的主机名或IP地址，此处为本地主机
#    host: localhost
    host: redis
    # 指定连接Redis服务器所需的密码，此处为空表示无密码访问
    password:
    timeout: 5000  # 增加超时时间
    lettuce:
        pool:
          max-active: 50
          test-while-idle: true  # 启用空闲检测
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/mall-auth/oauth/token"
      - "/mall-auth/rsa/publicKey"
      - "/mall-search/**"
      - "/mall-portal/sso/login"
      - "/mall-portal/sso/register"
      - "/mall-portal/sso/getAuthCode"
      - "/mall-portal/home/**"
      - "/mall-portal/product/**"
      - "/mall-portal/brand/**"
      - "/mall-admin/admin/login"
#      - "/mall-admin/admin/info"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有监控端点
  endpoint:
    health:
      show-details: always #总是显示健康检查详情
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # 网关路由日志
    org.springframework.security: ERROR      # 避免安全日志干扰
    reactor.netty.http: WARN                 # 网络层日志控制